# Configuration file for training with both texture and geometry features

paths:
  # Geometry data paths
  mesh_dir: "/path/to/train/meshes"
  label_dir: "/path/to/train/labels"
  json_dir: "/path/to/train/features"
  
  # Texture data paths
  texture_dir: "/path/to/train/textures"
  
  # Validation paths
  val_mesh_dir: "/path/to/val/meshes"
  val_label_dir: "/path/to/val/labels"
  val_json_dir: "/path/to/val/features"
  val_texture_dir: "/path/to/val/textures"
  
  # Model paths
  checkpoint_pertrain: "/path/to/pretrained/encoder.pth"
  log_dir: "/path/to/logs"
  checkpoint_dir: "/path/to/checkpoints"

training:
  epochs: 100
  batch_size: 8
  clusters_per_batch: 4
  accumulation_steps: 1
  resume: false
  use_pretrained: true
  num_unfrozen_encoder_layers: 2  # or "all" to unfreeze everything
  weight_decay: 1e-4
  ema_decay: 0.9999
  use_ema: true
  ignore_index: null  # Set to class index to ignore, or null to use all classes
  layer_wise_lr_decay: [10, 2]  # [head_multiplier, decay_factor]

model:
  # Geometry features
  feature_dim: 27  # Adjust based on your geometry features
  embedding_dim: 256
  num_heads: 4
  num_attention_blocks: 4
  n_classes: 10  # Adjust based on your number of classes
  n_clusters: 16
  faces_per_cluster: 50
  use_pe: true
  gradinat_ac: false
  dropout: 0.1
  include_normals: true
  additional_geometrical_features: false
  
  # Hierarchical processing
  use_hierarchical: false
  
  # Texture features
  use_texture: true
  texture_embed_dim: 128
  fusion_method: "gated"  # Options: "gated", "concat", "add"
  max_texture_pixels: 64
  texture_patch_size: 16

optimizer:
  type: "AdamW"
  learning_rate: 0.001

augmentation:
  rotation_range: 15
  scale_range: [0.9, 1.1]
  noise_std: 0.01
  flip_probability: 0.5
  mode: "RSN"

# Class weights (optional)
# class_weights:
#   class_percentages: [0.1, 0.2, 0.15, 0.15, 0.1, 0.1, 0.05, 0.05, 0.05, 0.05]
